package com.opencv.jni;

public interface opencvConstants {
    public static final int CV_16S;
    public static final int CV_16SC1;
    public static final int CV_16SC2;
    public static final int CV_16SC3;
    public static final int CV_16SC4;
    public static final int CV_16U;
    public static final int CV_16UC1;
    public static final int CV_16UC2;
    public static final int CV_16UC3;
    public static final int CV_16UC4;
    public static final int CV_32F;
    public static final int CV_32FC1;
    public static final int CV_32FC2;
    public static final int CV_32FC3;
    public static final int CV_32FC4;
    public static final int CV_32S;
    public static final int CV_32SC1;
    public static final int CV_32SC2;
    public static final int CV_32SC3;
    public static final int CV_32SC4;
    public static final int CV_64F;
    public static final int CV_64FC1;
    public static final int CV_64FC2;
    public static final int CV_64FC3;
    public static final int CV_64FC4;
    public static final int CV_8S;
    public static final int CV_8SC1;
    public static final int CV_8SC2;
    public static final int CV_8SC3;
    public static final int CV_8SC4;
    public static final int CV_8U;
    public static final int CV_8UC1;
    public static final int CV_8UC2;
    public static final int CV_8UC3;
    public static final int CV_8UC4;
    public static final int CV_AUTO_STEP;
    public static final int CV_CN_MAX;
    public static final int CV_CN_SHIFT;
    public static final int CV_DEPTH_MAX;
    public static final int CV_MAGIC_MASK;
    public static final int CV_MAT_CN_MASK;
    public static final int CV_MAT_CONT_FLAG;
    public static final int CV_MAT_CONT_FLAG_SHIFT;
    public static final int CV_MAT_DEPTH_MASK;
    public static final int CV_MAT_MAGIC_VAL;
    public static final int CV_MAT_TYPE_MASK;
    public static final int CV_SUBMAT_FLAG;
    public static final int CV_SUBMAT_FLAG_SHIFT;
    public static final String CV_TYPE_NAME_MAT;
    public static final int CV_USRTYPE1;

    static {
        CV_CN_MAX = opencvJNI.CV_CN_MAX_get();
        CV_CN_SHIFT = opencvJNI.CV_CN_SHIFT_get();
        CV_DEPTH_MAX = opencvJNI.CV_DEPTH_MAX_get();
        CV_8U = opencvJNI.CV_8U_get();
        CV_8S = opencvJNI.CV_8S_get();
        CV_16U = opencvJNI.CV_16U_get();
        CV_16S = opencvJNI.CV_16S_get();
        CV_32S = opencvJNI.CV_32S_get();
        CV_32F = opencvJNI.CV_32F_get();
        CV_64F = opencvJNI.CV_64F_get();
        CV_USRTYPE1 = opencvJNI.CV_USRTYPE1_get();
        CV_MAT_DEPTH_MASK = opencvJNI.CV_MAT_DEPTH_MASK_get();
        CV_8UC1 = opencvJNI.CV_8UC1_get();
        CV_8UC2 = opencvJNI.CV_8UC2_get();
        CV_8UC3 = opencvJNI.CV_8UC3_get();
        CV_8UC4 = opencvJNI.CV_8UC4_get();
        CV_8SC1 = opencvJNI.CV_8SC1_get();
        CV_8SC2 = opencvJNI.CV_8SC2_get();
        CV_8SC3 = opencvJNI.CV_8SC3_get();
        CV_8SC4 = opencvJNI.CV_8SC4_get();
        CV_16UC1 = opencvJNI.CV_16UC1_get();
        CV_16UC2 = opencvJNI.CV_16UC2_get();
        CV_16UC3 = opencvJNI.CV_16UC3_get();
        CV_16UC4 = opencvJNI.CV_16UC4_get();
        CV_16SC1 = opencvJNI.CV_16SC1_get();
        CV_16SC2 = opencvJNI.CV_16SC2_get();
        CV_16SC3 = opencvJNI.CV_16SC3_get();
        CV_16SC4 = opencvJNI.CV_16SC4_get();
        CV_32SC1 = opencvJNI.CV_32SC1_get();
        CV_32SC2 = opencvJNI.CV_32SC2_get();
        CV_32SC3 = opencvJNI.CV_32SC3_get();
        CV_32SC4 = opencvJNI.CV_32SC4_get();
        CV_32FC1 = opencvJNI.CV_32FC1_get();
        CV_32FC2 = opencvJNI.CV_32FC2_get();
        CV_32FC3 = opencvJNI.CV_32FC3_get();
        CV_32FC4 = opencvJNI.CV_32FC4_get();
        CV_64FC1 = opencvJNI.CV_64FC1_get();
        CV_64FC2 = opencvJNI.CV_64FC2_get();
        CV_64FC3 = opencvJNI.CV_64FC3_get();
        CV_64FC4 = opencvJNI.CV_64FC4_get();
        CV_AUTO_STEP = opencvJNI.CV_AUTO_STEP_get();
        CV_MAT_CN_MASK = opencvJNI.CV_MAT_CN_MASK_get();
        CV_MAT_TYPE_MASK = opencvJNI.CV_MAT_TYPE_MASK_get();
        CV_MAT_CONT_FLAG_SHIFT = opencvJNI.CV_MAT_CONT_FLAG_SHIFT_get();
        CV_MAT_CONT_FLAG = opencvJNI.CV_MAT_CONT_FLAG_get();
        CV_SUBMAT_FLAG_SHIFT = opencvJNI.CV_SUBMAT_FLAG_SHIFT_get();
        CV_SUBMAT_FLAG = opencvJNI.CV_SUBMAT_FLAG_get();
        CV_MAGIC_MASK = opencvJNI.CV_MAGIC_MASK_get();
        CV_MAT_MAGIC_VAL = opencvJNI.CV_MAT_MAGIC_VAL_get();
        CV_TYPE_NAME_MAT = opencvJNI.CV_TYPE_NAME_MAT_get();
    }
}
